from pathlib import Path
from typing import Any, List

from fastapi.routing import APIRoute

from pydantic2protobuf.services.pydantic_to_proto import pydantic_to_proto
from pydantic2protobuf.tools.format import new_line, tab
from pydantic2protobuf.tools.from_fastapi import extract_model_meta_classes
from pydantic2protobuf.tools.from_pydantic import is_type_iterable

proto_header = f"""// Generated by {Path(__file__).resolve()}.  DO NOT EDIT!
syntax = "proto3";

// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct
import "google/protobuf/struct.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";"""


def add_stream_qualifier(outer_type: Any) -> str:
    """"""
    return f"{'stream ' if is_type_iterable(outer_type) else ''}"


def gen_service_request_proto(route: APIRoute) -> str:
    """"""
    request_body_params = route.dependant.body_params
    return (
        f"{add_stream_qualifier(request_body_params[0].outer_type_)}{request_body_params[0].type_.__name__}"
        if request_body_params
        else "google.protobuf.Empty"
    )


def gen_service_response_proto(route: APIRoute) -> str:
    """"""
    response_field = route.response_field
    return (
        f"{add_stream_qualifier(response_field.outer_type_)}{response_field.type_.__name__}"
        if response_field
        else "google.protobuf.Empty"
    )


def route_to_proto_service(route: APIRoute, prefix: str = tab) -> str:
    """"""
    return f"{prefix}rpc do_{route.name} ({gen_service_request_proto(route)}) returns ({gen_service_response_proto(route)});"


def proto_gen_services(service_name, routes) -> str:
    """"""
    return f"""service {service_name} {{
{new_line.join(map(route_to_proto_service, routes))}
}}"""


def proto_gen_messages(routes: List[APIRoute]) -> str:
    """"""
    return new_line.join(
        pydantic_to_proto(model_meta_class) for model_meta_class in set(extract_model_meta_classes(routes))
    )


def routes_to_proto(routes: List[APIRoute], service_name: str = "Service") -> str:
    """"""
    return (2 * new_line).join(
        (
            proto_header,
            proto_gen_services(service_name, routes),
            proto_gen_messages(routes),
        )
    )
